### ISSUE TITLE
Find services via DNS rather than registry

### ISSUE THREAD

**Issue by jschewebbn** [DescartesResearch/TeaStore#129] opened 2019-06-26 16:32 UTC
I'm doing some research where I'm using DNS to do load balancing. Looking through the code it appears that the dependent services (auth, persistence, etc) are found by asking the registry. Is this correct?

I was wondering if it's possible for TeaStore to find the dependent services via DNS lookups instead of the registry?

**Comment by SimonEismann** [comment] 2019-06-27 08:50
The available instances of the depended services are pulled from the registry every five seconds and then each request is load-balanced between the available instances. 

I think you could use a similar workaround as the Kubernetes deployment (https://github.com/DescartesResearch/TeaStore/wiki/Getting-Started#3-run-the-teastore-on-a-kubernetes-cluster). Here, each service instance registers with the service name (dns address in your case) and so no matter how many instances are available, the registry thinks only a single instance is available and so the services direct all calls to the service name (dns address in your case). 

What type of deployment are you looking to use, docker or kubernetes? If you can give me an example of how your DNS names look, I can try to put an example together.

**Comment by jschewebbn** [comment] 2019-06-27 13:30
I am deploying with docker containers. The service names will be something like web-ui.internal, auth.internal, persistence.internal, etc. Where "internal" is our custom DNS domain that is used in our test network and "web-ui", "auth", etc. is the name of the service to be connected to.

Looking at the Kubernetes document that you referenced, it appears that setting the `HOST_NAME` environment variable for each container specifies the name that it will report to the registry. Is that correct? If so, this is much easier to accomplish than I thought it would be.

**Comment by SimonEismann** [comment] 2019-06-27 13:41
Exactly, each service instance registers its HOST_NAME + SERVICE_PORT to the registry. If multiple service report the same HOST_NAME + SERVICE_PORT pair, then it is still only contained once in the registry. All other services periodically pull the list of all service instances from the registry and load balance all request between them. So if for example all recommender instances register as for example recommender.internal + 8080, then all requests to the recommender will be sent to recommender.internal:8080. So if recommender.interal:8080 correctly loadbalances between the recommender instances, everything should be working as intended.

I'll close this issue for now, feel free to reopen it if any issue come up.

**Closed by SimonEismann** 2019-06-27 13:41 UTC

**Comment by jschewebbn** [comment] 2019-06-27 13:45
That is exactly what I'm looking for. Thank you very much for the details!
